#!/bin/bash

# Note: don't forget to login to registry.gitlab.com: `docker login registry.gitlab.com`

ANSIBLE_NAME=${ANSIBLE_NAME:-ansible}
ANSIBLE_IMG=
ANSIBLE_MOUNT_DIR=${ANSIBLE_MOUNT_DIR:-${PWD}}

docker run -it --rm \
  --name ${ANSIBLE_NAME} \
  --network host \
  -v "${ANSIBLE_MOUNT_DIR}":/workdir -w /workdir \
  ${ANSIBLE_IMG} "$@"
